name: material_github_searcher_workspace
publish_to: none

environment:
  sdk: 3.12.2

workspace:
  - apps/app
  - packages/application
  - packages/dependency_override
  - packages/designsystem
  - packages/domain
  - packages/foundation
  - packages/infrastructure/mock

dev_dependencies:
  altive_lints: 4.0.0
  test: 1.31.0
