name: application
description: Application use cases, state, and injected repository providers.
publish_to: none
version: 0.1.0

environment:
  sdk: 3.12.2

dependencies:
  domain:
    path: ../domain
  foundation:
    path: ../foundation

resolution: workspace
