name: infrastructure_mock
description: Test and development repository implementations.
publish_to: none
version: 0.1.0

environment:
  sdk: 3.12.2

dependencies:
  domain:
    path: ../../domain
  meta: 1.18.0

dev_dependencies:
  test: 1.31.0

resolution: workspace
