name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    uses: ./.github/workflows/detect_ci_changes.yaml

  test:
    needs: changes
    if: needs.changes.outputs.test == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: ./.github/actions/setup-flutter

      - name: Install dependencies
        run: flutter pub get

      - name: Test SDK synchronization tool
        run: dart test test/tools

      - name: Test Flutter app
        working-directory: apps/app
        run: flutter test
